### ISSUE TITLE
Implementing multi-step exercises?

### ISSUE THREAD

**Issue by IanWhitney** [exercism/discussions#5] opened 2016-03-31 12:27 UTC
Today my Kata group discussed solutions for Queen Attack. We all thought it would be interesting to have some follow-up exercises. The idea is that the student would build-on and modify their code from the earlier exercises to solve later exercises.

One possible set of exercises could be:
1. Can 2 queens attack each other? (this is the standard set of queen attack tests)
2. Can 2 knights attack each other?
3. Given a board with a queen and knight, who can attack whom?
4. Given a board with 2 queens and 2 knights, who can attack whom?

Each exercise would introduce a new wrinkle into the existing code. Moving from Exercise 1 to 2 would get students thinking about different piece types, what behavior they have in common and what behavior they do not.

2 -> 3 Would introduce the ideas of non-reciprocal attacks. If queen A can attack queen B, then the reverse is true. Same for knights. But if a queen can attack a knight, then the reverse is false.

3 -> 4 Is a big leap. You have to introduce a board concept, because you have to start thinking about other pieces being in your way. Yes, that queen might be diagonal from your queen, but there's a knight in your path. Etc.

And so on. You can take this pretty far, obviously.

**Comment by kytrinyx** [comment] 2016-03-31 13:34
I think this is a great idea, and that it would be an excellent extension of the iterative approach that Exercism already has. Off the top of my head I have no idea how we would implement it, nor what it would look like in terms of the user experience, and I would love to see a discussion here about how we might go about it, or perhaps how we might go about introducing a naive version of it in order to experiment with it.

**Comment by petertseng** [comment] 2016-03-31 14:03
This is interesting. And even without any special support for it, it's already possible to add new exercises that are related to one another, it's just that there's no way to express to students their relation. Currently we have series which is a potential precursor to largest series product (Depending on how you choose to implement LSP). Obviously it would be better if there were some way to show they're related.

Wasn't there a previous discussion somewhere of a kind of track-within-a-track kind of thing? I am struggling to find the issue now, but I was going to see if it was suitable to used for this kind of thing.

**Comment by IanWhitney** [comment] 2016-03-31 14:30
I think there are two big hurdles:

1. Showing that they are related
2. Giving students starter code should they start in the middle of the series

I think we can address the first point through the Readme and the tests. The readme part is pretty self-explanitory. For the tests I think the tests in the later exercises should contain the tests from the earlier exercises.

Using my Chess suggestion as an example. The 2nd exercise (implementing knights) should also run the tests for the first part (implementing queens). Since the goal is to show the growth of code as new requirements are added, we want to also ensure that students don't introduce regression bugs.

I think we can handle the 2nd hurdle by linking to the example code from the previous exercise. So if a student starts with Knights, we link to the example code for implementing Queens.

**Comment by kotp** [comment] 2016-03-31 17:14
Showing that they are related should not be such a big deal.  We already have the code generate the test file.  Just have it refer to their version of the prior exercise.  The README and the tests are our very capable ways of communicating with the person any thing that needs to be communicated.

We already have them modify the tests by having them delete the 'skip' or comment it out, etc.  Have a line that communicates that they can require their prior solution.  The prior tests for the previous exercise already drives the API.

I don't see where this would be a problem., except for when someone moves to a new machine, and doesn't have their old solutions.  Still, I think the cli already has a way to pull down last solutions?

**Comment by kytrinyx** [comment] 2016-03-31 19:44
Right now each individual exercise is stand-alone. It doesn't assume anything about which exercises you've solved or in which order.

If you skip the first in a series, should it automatically skip you past all the related ones?

Should follow-on exercises be displayed on the website as being available to solve? Or should you just get them as a "step 2" after you've solved the first one?

**Comment by IanWhitney** [comment] 2016-03-31 19:47
I know students can choose to fetch specific exercises, but isn't the default to simply fetch the next exercise in that language's config.json?

As for starting in the middle, I think that's handled by a link to starter code.

**Comment by kytrinyx** [comment] 2016-03-31 20:52
Yeah, the default is to fetch the next one. Maybe that's good enough.

**Comment by IanWhitney** [comment] 2016-03-31 23:06
Putting some of this conversation together into an example, here's what  I think we have. I'll use Ruby as the example language.

`config.json`
```json
"problems": [
  ...
  "queen-attack",
  "knight-attack",
  "queen-knight-attack",
  ...
]
```

The description of Knight Attack has some text like:

```
This exercise follows Queen Attack. If you have not done that problem, you can do so before starting this one or you can get the code from _link_to_ruby_queen_attack_example_
```

The test file for Knight Attack would include the tests from Queen Attack. I'm not sure the best way to do this. If the student has fetched Queen Attack, then we could `require_relative` it in. But I'm not sure if all languages can do that (I would think they could, but don't know). If a student hasn't fetched Queen Attack then this would fail. Perhaps we'd have to require that students at least fetch Queen Attack before doing Knight Attack?

Alternatively, the entire test suite of Queen Attack could be copied into Knight Attack's tests. But that seems like a maintenance problem. Every change to the Queen Attack test suite would have to be ported to each subsequent test suite.

**Comment by IanWhitney** [comment] 2016-04-01 01:47
I have a semi-working version of this in Rust as well. If there's interest, I can put together a PR over the next few days and then we'd have an actual implementation to look at and discuss.

**Comment by kytrinyx** [comment] 2016-04-01 21:15
I think you're right that copying the queen tests into knight tests would add a potential maintenance burden.

Can we get away with instructing people to (a) fetch the queen exercise if they haven't already and (b) copy the queen tests (and perhaps their solution) into the new place before getting started?

Would the code they submit include the queens-only code, or just the new stuff? (Would they be writing it in the same file?)

**Comment by kotp** [comment] 2016-04-01 21:36
Of course there is a maintenance cost.  But the queen tests and the knight tests may be individual.  Nothing yet to say that Knights attack depends on something from Queens attack.

A follow on exercise where it is Knights Vs Queens may use behavior previously established, those contracts being testable and loadable, due to knowing the folder structure.  A test that fails to load the require library should report that the exercise should be completed first, as this one relies on the prior exercise.

I don't think there should be any copying going on.  Not to the other exercise folder.  This is an anti-pattern in design anyway, we don't want duplicate code.  We can use the code that is already there, or that is required to be where it was to get a 'passing' exercise.

From the users standpoint, the require_relative is '../queen_attack_test' and is "known" so there is no copying required, just a reference to where it is expected to be.  If the require fails (returns false) then we can assume that it is not there, and can suppose that it may be not completed.  However, if it is completed, it could be fetched.

Fetching the problem if it has been already solved is not a problem, we either indicate for them to use the `exercism fetch <track> queen_attack`, if that is the one that is missing, or refer them to use `exercism --help` with a hint that they will need to fetch their solution, or fetch the exercise and complete it.

The "maintenance cost" then is the burden of the nitpiker, to complete the prior exercise to specifications, the "development cost" is to design it so that it complies with anything else that it relies on.

**Comment by IanWhitney** [comment] 2016-04-01 21:51
I think I initially said that it would be nice if running the Knight tests also ran the Queen tests. But thinking about it more, it is probably totally unnecessary since the Knight tests will implicitly test Queen behavior. For example:

`test_queen_attack.rb`
```ruby
def test_horizontal_attack
  white_queen = Queen.new([2,4])
  black_queen = Queen.new([2,6])
  assert white_queen.can_attack?(black_queen)
end
```

Then in `test_knight_attack`

```
def test_knight_can_attack_queen
  knight = Knight.new([2,4])
  queen = Queen.new([3,5])
  assert knight.can_attack?(queen)
  refute queen.can_attack?(knight)
end
```
If the student has broken the queen's implementation, that test will raise an error or fail. Hopefully.

So there's probably no reason to run the Queen tests while working on the Knight implementation.

**Comment by kotp** [comment] 2016-04-01 22:18
@IanWhitney That is what I am thinking.  

The exercism client side structure is such that this line should be sufficient to find out if we have a Queen to even use, so in the test, may be something like this:

``` ruby
begin
  require_relative '../queen_attack/queen_attack'
rescue NoLoadError => e
  STDERR.puts "I can not load the Queen Attack exercise files, please either fetch your solution for that exercise, or complete that exercise before attempting this one."
  STDERR>puts e
end
```

Not tested, but just a model.

**Comment by kytrinyx** [comment] 2016-04-01 23:32
> A follow on exercise where it is Knights Vs Queens may use behavior previously established, those contracts being testable and loadable, due to knowing the folder structure.

I don't know if all languages will allow loading based on knowing relative paths.

**Comment by kotp** [comment] 2016-04-02 00:07
Neither do I, but if there is any way to load code that is not in the same file, then that is something the ones familiar with their tracks are likely to be able to do.  The problem is common and so I would be surprised if there is not a mechanism.

Even if the 'relative path' type functionality isn't built in, I think all languages have a way to get the current working path.  From there it may be (and should be) trivial.

**Comment by IanWhitney** [comment] 2016-04-02 00:25
Here's an example of Knight Attack in Rust

https://github.com/IanWhitney/xrust/commit/6fad7a9b1b4adcb0bfb4822d83d7b87a710b61c2

Some things to note:

- Rust does not (to my knowledge) have anything like `require_relative`. But I'm able to bring in my queen-attack solution as an [external crate](https://github.com/IanWhitney/xrust/commit/6fad7a9b1b4adcb0bfb4822d83d7b87a710b61c2#diff-63ed83a776584a279314d275ebc18054R6)
- Implementing the Knight stuff without introducing a bunch of duplication required me to refactor my initial Queen code. I think this is good! But I've also made sure to call this out in [my comment at the top of the Knight tests](https://github.com/IanWhitney/xrust/commit/6fad7a9b1b4adcb0bfb4822d83d7b87a710b61c2#diff-a207356c96b85586a1dcca01c8b8b0c9R16)

**Comment by IanWhitney** [comment] 2016-04-02 00:38
Another thing I learned while doing that demo is that multi-step exercises will be easier if implemented all at once. At least in languages like Rust, they will. While implementing the Knight tests I found that I needed to fix some of the Queen API, which meant going back and updating all of the Queen tests.

**Comment by kytrinyx** [comment] 2016-04-02 01:58
> multi-step exercises will be easier if implemented all at once.

Yeah, I can see where that would be true. Whenever I finally understand where I'm going with something I have to go back and tweak all my ideas that led to it.

**Comment by IanWhitney** [comment] 2016-04-07 20:01
Another hurdle I just realized. If a nitpicker is looking at the code for a later step, they can't easily see the code from the earlier step. So, if someone is nitpicking Knight Attack, they can't easily see my Queen Attack code.

**Comment by kytrinyx** [comment] 2017-06-04 21:46
We are doing a complete redesign of Exercism from the core principles/questions on up. Today we published the first set of documents that explore questions around enhancing and supporting people's motivation to learn and practice on Exercism: https://github.com/exercism/docs/blob/master/about/conception/README.md

Particularly relevant to this question is the section on "expectancies of success" and the related document about track progression where we explore how to better structure tracks to support people's success with learning a language.

I think that multi-step exercises would fit naturally into this new structure.

I don't know if there's more to explore about the topic directly, I just wanted to pop in to say that _yes_, this is something we should absolutely consider going forward.

Meanwhile, since there are no direct action items, I'm going to close this—if there *are* and I've just missed them, please feel free to reopen it (in that case, please help clarify what needs to be done).

**Closed by kytrinyx** 2017-06-04 21:46 UTC
Labels: concerning/product

**Comment by kytrinyx** [comment] 2017-06-04 21:52
Oh, also:  We have an issue open requesting thoughts and feedback on these design documents: https://github.com/exercism/discussions/issues/154
