### ISSUE TITLE
Use SitOnIt-CI to enforce minimum lifetime for Pull Requests

### ISSUE THREAD

**Issue by cmccandless** [exercism/discussions#218] opened 2018-06-21 12:57 UTC
*This issue was initially created in the problem-specifications repository. I believe it is most relevant there, so I will leave the original issue open, but [per suggestion](https://github.com/exercism/problem-specifications/issues/1244#issuecomment-391395137) by @rpottsoh, I am opening discussion here as well.*

From exercism/problem-specifications#1244:

> I've noticed it's common in this repository to wait for a while before merging a PR that has been rapidly reviewed in order to give other maintainers a chance to comment themselves. At this time, this is more of an unwritten courtesy; what about making it policy?

> [SitOnIt-CI](https://github.com/apps/sitonit-ci) enforces just this, and is configurable per-repository.

> I would suggest 24 hours as a required wait time; this is the default and requires no configuration. 

> As with any CI status service, any user with admin privileges on the repository may install the app or override it to merge anyway.

> I would love to see some discussion about the pros/cons of enforcing wait times.

**Comment by coriolinus** [comment] 2018-06-21 13:03
The issue is that the required wait time varies according to the situation.

Very often when reviewing a new exercise, I'll perform my review, and then wait a week or so to ensure everyone else gets their shot. However, it doesn't make sense to enforce a week's delay on PRs in general, because there are other items, such as adding topics to exercises which don't have them assigned, which can be merged immediately, and for which there is some time pressure. 

This isn't a vote against installing the tool, just a note that I'd be very reluctant to use it for the rust track because there is no universally appropriate delay time. Perhaps it might be useful for other tracks.

**Comment by cmccandless** [comment] 2018-06-21 13:07
> The issue is that the required wait time varies according to the situation.

My thoughts exactly. Which is why I initially suggested this only for the problem-specifications repository, as changes there tend to be more consistent in type.

*Also, a [planned feature](cmccandless/sitonit#23) would add the ability to configure/override wait time per PR for any maintainer of the repository.*

**Comment by rpottsoh** [comment] 2018-06-21 13:12
> Also, a planned feature would add the ability to configure/override wait time per PR for any maintainer of the repository.

:+1:

**Comment by kytrinyx** [comment] 2018-08-03 01:29
I'm not convinced that the tool would be generally useful for all Exercism tracks, but if you want to try it out on the track you're maintaining please let me know and I'll get it installed for you.

**Closed by kytrinyx** 2018-08-03 01:29 UTC
