### ISSUE TITLE
Move/rename TRACK_HINTS.md

### ISSUE THREAD

**Issue by rbasso** [exercism/discussions#147] opened 2017-06-01 08:51 UTC
As mentioned in https://github.com/exercism/docs/pull/35#discussion_r119214614, the `exercises` folder may not be the best place to keep the `TRACK_HINTS.md` file. The contenders until now are:

- `/TRACK_HINTS.md` (move it to the root of the repository)
- `/exercises/TRACK_HINTS.md` (keep it where it is)
- `/docs/TRACK_HINTS.md` (move to the documentation folder)
- `/docs/HINTS.md` (move and rename)

I think the file belongs to the `docs` folder. If we decide to move it there, it could also be renamed `HINTS.md`, because everything in the track's repository is unavoidably repository-related. 

As a bonus from moving the file, wildcard expansion in the `exercises` folder would give a list of the implemented exercises! 😁

**Comment by mhinz** [comment] 2017-06-01 09:09
For the [Vimscript track](https://github.com/exercism/xvimscript), we also put `TRACK_HINTS.md` into the root directory.

I agree that `exercises/TRACK_HINTS.md` doesn't make much sense.

And I'm against moving it to `docs/`, because I consider it the _user documentation_. Things in there end up on http://exercism.io/languages/vimscript.

`TRACK_HINTS.md` should explain how to contribute to the track repo. I consider it the more detailed version of `README.md`. The latter could reference the former: _"For more information about adding a new exercise see TRACK_HINTS.md."_

**Comment by rbasso** [comment] 2017-06-01 09:19
> TRACK_HINTS.md should explain how to contribute to the track repo. I consider it the more detailed version of README.md. 

I'm not sure if this is the intended use of `TRACK_HINTS.md`, @mhinz. If you are right, we *definitely shouldn't be including it* in each of the exercise's `README.md`.

**Comment by Insti** [comment] 2017-06-01 09:28
`TRACK_HINTS.md` is included in the Readme for every exercise, and should include things like: "Here is how you run the tests in this language"

@mhinz is not using it as intended.

> TRACK_HINTS.md should explain how to contribute to the track repo

This information belongs in a `CONTRIBUTING.md` that lives in the repository root.

**Comment by mhinz** [comment] 2017-06-01 09:43
So, what _is_ the intention of `TRACK_HINTS.md`?

**Comment by Insti** [comment] 2017-06-01 10:21
> what is the intention of TRACK_HINTS.md? What kind of information should it contain that couldn't be put into CONTRIBUTING.md?

TRACK_HINTS.md is included in the Readme for every exercise, and should include things like: "Here is how you run the tests in this language"

It's not usually got anything to do with contributing to the track.

Here are the tracks that have it:
```
tracks/ceylon/exercises/TRACK_HINTS.md
tracks/go/exercises/TRACK_HINTS.md
tracks/haskell/exercises/TRACK_HINTS.md
tracks/lua/exercises/TRACK_HINTS.md
tracks/r/exercises/TRACK_HINTS.md
tracks/ruby/exercises/TRACK_HINTS.md
tracks/rust/exercises/TRACK_HINTS.md
```

It used to be called `SETUP.md` and this location is still supported, but not encouraged.

```
tracks/bash/SETUP.md
tracks/coffeescript/SETUP.md
tracks/coldfusion/SETUP.md
tracks/cpp/SETUP.md
tracks/crystal/SETUP.md
tracks/c/SETUP.md
tracks/dlang/SETUP.md
tracks/ecmascript/SETUP.md
tracks/elixir/SETUP.md
tracks/elm/SETUP.md
tracks/erlang/SETUP.md
tracks/factor/SETUP.md
tracks/fsharp/SETUP.md
tracks/groovy/SETUP.md
tracks/haxe/SETUP.md
tracks/idris/SETUP.md
tracks/javascript/SETUP.md
tracks/java/SETUP.md
tracks/julia/SETUP.md
tracks/kotlin/SETUP.md
tracks/lfe/SETUP.md
tracks/lisp/SETUP.md
tracks/mips/SETUP.md
tracks/nasm/SETUP.md
tracks/nim/SETUP.md
tracks/objective-c/SETUP.md
tracks/ocaml/SETUP.md
tracks/perl5/SETUP.md
tracks/perl6/SETUP.md
tracks/php/SETUP.md
tracks/plsql/SETUP.md
tracks/pony/SETUP.md
tracks/powershell/SETUP.md
tracks/prolog/SETUP.md
tracks/purescript/SETUP.md
tracks/python/SETUP.md
tracks/racket/SETUP.md
tracks/scala/SETUP.md
tracks/sml/SETUP.md
tracks/swift/SETUP.md
tracks/tcl/SETUP.md
tracks/teco/SETUP.md
tracks/vbnet/SETUP.md
```
Have a read through some of them and see what they contain.

**Comment by petertseng** [comment] 2017-06-01 16:03
This raises an additional interesting question such as "why are the contents of TRACK_HINTS.md NOT exactly the same as TESTS.md?" Indeed, that question was asked in https://github.com/exercism/x-common/issues/229.

After experiencing it in `exercises`, I am finding it makes less sense there.

I'm going to throw another name for consideration: `docs/APPEND_TO_README.md`. I find it a bit unsatisfying though since until now the names have told us *what the file is*, not *what is to be done with the file*. Although it is a bit of an outlier in the `docs` since all the other files in `docs` do appear in http://exercism.io/languages/yourlanguage. Tough choice, eh?

My current best *location* is somewhere in `docs`, but I'm having a hard time thinking of a name for it!

**Comment by Insti** [comment] 2017-06-01 17:37
> why are the contents of TRACK_HINTS.md NOT exactly the same as TESTS.md?

Because TRACK_HINTS need not be about TESTS.

**Comment by kytrinyx** [comment] 2017-06-02 02:48
I honestly like the idea of keeping the track hints in the docs/ directory. It is end-user documentation, it just happens to not get included on the site.

I don't have very strong feelings about the file name. I'd be ok with either TRACK_HINTS.md or EXERCISE_HINTS.md or HINTS.md

**Comment by Insti** [comment] 2017-06-02 07:01
> names have told us what the file is, not what is to be done with the file. 

*_HINTS is quite vague and it appears from the discussion so far that it requires knowledge about what is going to be done with it to know what to put in it.

So for this file what is to be done with the file is the important thing.

How about: `docs/THIS_WILL_BE_INCLUDED_IN_EVERY_EXERCISE_README.md`

Although there is  might be a nicer way of saying that.

**Comment by petertseng** [comment] 2017-06-02 18:15
I find my suggestion of `docs/APPEND_TO_README.md` unsatisfying since it's not really appended. The order is currently: x-common specification, exercise's HINTS.md, the file we are currently talking about, source, "you can submit incomplete submissions". So it's not being appended unless you pretend the last two elements don't exist.

* APPEND_TO_README.md
* README_INSERT.md
* README_INCLUDE.md
* INCLUDE_IN_README.md
* INSERT_INTO_README.md

**Comment by petertseng** [comment] 2017-06-02 18:15
Prepend the appropriate directory to all those paths.

**Comment by kytrinyx** [comment] 2017-06-03 02:21
My favorite names so far are `README_INSERT.md` and `EXERCISE_HINTS.md` (or maybe `GLOBAL_EXERCISE_HINTS.md`)

**Comment by Insti** [comment] 2017-06-03 16:42
`docs/EXERCISE_README_INSERT.md` ?

**Comment by kytrinyx** [comment] 2017-06-03 17:15
> docs/EXERCISE_README_INSERT.md

@Insti this is my new favorite.

**Comment by kytrinyx** [comment] 2017-06-09 03:02
OK, it's been a week with no new suggestions.

My vote is for `docs/EXERCISE_README_INSERT.md`.

If I don't hear any good arguments for something better, this is what I'm going with.

**Comment by Insti** [comment] 2017-06-09 07:09
If you create an issue in Trackler I can help out with this (unless you want to do it yourself).

**Comment by kytrinyx** [comment] 2017-06-09 13:31
Thanks @Insti!

I've opened a top level tracking issue in meta (I'm experimenting, bear with me), and a specific issue in trackler: https://github.com/exercism/trackler/issues/62

I'll prepare the script so that we can run that as soon as we've merged a fix for supporting the file.

**Comment by kytrinyx** [comment] 2017-06-09 13:31
I'm going to close this issue since we're now tracking the actionable tickets elsewhere. Thanks everyone! ✨

**Closed by kytrinyx** 2017-06-09 13:31 UTC
Labels: concerning/open-source, todo/decision
